#!/usr/bin/env bash
# Install and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                    echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 187997-web-01 54.237.217.84:80 check
   server 187997-web-02 3.85.136.124:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
